global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: aimilivpn
    static_configs:
      # 所有服务使用 host 网络模式，直接访问 localhost
      - targets: ["localhost:9798"]
        labels:
          instance: aimilivpn
